MyLegacyMaps/Controllers/MapsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MLM.Logging;
using MLM.Persistence.Interfaces;
using MyLegacyMaps.Models;
using MyLegacyMaps.Extensions;
using MyLegacyMaps.Classes.Cookies;

namespace MyLegacyMaps.Controllers
{
    public class MapsController : Controller
    {
        private IMapsRepository mapsRepository = null;
        private IPartnerLogosRepository logosRepository = null;
        private ILogger log = null;
        private ICookieHelper cookies = null;
      

        public MapsController(IMapsRepository repositiory, IPartnerLogosRepository logosResource, ILogger logger, ICookieHelper cookieHelper)
        {
            mapsRepository = repositiory;
            logosRepository = logosResource;
            log = logger;
            cookies = cookieHelper;
        }

        /// <summary>
        /// Get Public List of Active Maps
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Get Public List of Active Maps
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<ActionResult> AdventureMaps(int? currentFilterId, int? page)
        {
            int mapTypeId = 0;
         
            try
            {
                //Read in Map Type drop down value and save in cookie
                if (currentFilterId.HasValue)
                {
                    mapTypeId = (int)currentFilterId.Value;
                    cookies.SetCookie(Constants.COOKIE_MAPTYPEID,
                        mapTypeId.ToString(), this.ControllerContext.HttpContext);
                }
                else
                {
                    //get selected value from cookie
                    mapTypeId = cookies.GetCookie<int>(Constants.COOKIE_MAPTYPEID,
                       this.ControllerContext.HttpContext);
                }

                var mapTypes = new List<MapType>();
                var respMapTypes = await mapsRepository.GetMapTypesAsync();                
                if (respMapTypes.IsSuccess())
                {
                    mapTypes = respMapTypes.Item.ToViewModel(false);                   
                    
                }

                //Get Maps by map type id
                var resp = await mapsRepository.GetMapsAsync(mapTypeId);
                if(!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }
                            
                //View
                ViewBag.mapTypes = mapTypes;
                ViewBag.CurrentFilter = (mapTypeId > 0)
                   ? mapTypes.Find(mt => mt.MapTypeId == mapTypeId).Name
                   : String.Empty;

                
                int pageNumber = (page ?? 1);
                var mapsViewModel = resp.Item.ToViewModel(false).OrderBy(m => m.Name);
                return View(mapsViewModel.ToPagedList(pageNumber, Constants.PAGE_SIZE));

            }
            catch(Exception ex)
            {
                log.Error(ex, "Error in MapsController GET Index");
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Get Public List of maps filtered by MapTypeId.
        /// </summary>
        /// <param name="values">ddlMapTypeId</param>
        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> AdventureMaps(FormCollection values)
        {
            int mapTypeId = 0;
            try
            {     
                //Read in May Type drop down value and save in cookie
                Int32.TryParse(values["ddlMapTypeId"], out mapTypeId);
                cookies.SetCookie(Constants.COOKIE_MAPTYPEID, 
                    mapTypeId.ToString(), this.ControllerContext.HttpContext);

                //Get Map Types
                ViewBag.mapTypes = await GetMapTypeOptions(mapTypeId);
               
                //Get Maps by Map TypeID
                var resp = await mapsRepository.GetMapsAsync(mapTypeId);
                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                //View
                var mapsViewModel = resp.Item.ToViewModel();
                return View(mapsViewModel.OrderBy(m => m.Name));                      
            }
            catch(Exception ex)
            {
                log.Error(ex, String.Format("Error in MapsController POST Index mapTypeId = {0}",
                    mapTypeId));
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Get Public List of Active Maps
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<ActionResult> RealEstateMaps(int? page)
        {
            int mapTypeId = 1;            
            try
            {               
                //Get Maps by map type id
                var resp = await mapsRepository.GetMapsAsync(mapTypeId);
                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                //View
                int pageNumber = (page ?? 1);
                var mapsViewModel = resp.Item.ToViewModel(true).OrderBy(m => m.Name);
                return View(mapsViewModel.ToPagedList(pageNumber, Constants.PAGE_SIZE));

            }
            catch (Exception ex)
            {
                log.Error(ex, "Error in MapsController GET Index");
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
    

        private async Task<SelectList> GetMapTypeOptions(int selectedMapTypeId)
        {
           // IEnumerable<SelectListItem> types = (from m in db.MapTypes where m.IsActive == true select m).AsEnumerable().OrderBy(m=>m.Name).Select(m => new SelectListItem() { Text = m.Name, Value = m.MapTypeId.ToString() });

           
            var resp = await mapsRepository.GetMapTypesAsync();
            if(!resp.IsSuccess())
            {
                return new SelectList(new List<MapType>(), "Value", "Text"); //empty list
            }
            var mapTypes = resp.Item.ToViewModel(false);

            IEnumerable<SelectListItem> types = mapTypes.OrderBy(m => m.Name).Select(m => 
                new SelectListItem() { Text = m.Name, Value = m.MapTypeId.ToString() });
            
            var mapTypeOptions =  (selectedMapTypeId > 0)
                    ? new SelectList(types, "Value", "Text", selectedMapTypeId)
                    : new SelectList(types, "Value", "Text");

            return mapTypeOptions;
        }


        // GET: Maps/Details/5
        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            try
            { 
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "missing id parameter");
                }

                var resp = await mapsRepository.GetMapAsync((int)id.Value);
                if(!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                var map = resp.Item.ToViewModel();

                if (map.IsRealEstateMap())
                {
                    var respLogos = await logosRepository.GetPartnerLogosAsync();
                    if (!respLogos.IsSuccess())
                    {
                        return new HttpStatusCodeResult(resp.HttpStatusCode);
                    }
                    ViewBag.PartnerLogos = respLogos.Item.ToViewModel();
                }
                return View(map);
            }
            catch (Exception ex)
            {
                log.Error(ex, "Error in MapsController GET Details id = {0} ",
                  (id.HasValue) ? id.Value.ToString() : "null");

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }           
        }

       
    }
}

MyLegacyMaps/Views/Shared/Info.cshtml
@{
   ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

MyLegacyMaps/Views/Shared/ProfileNav.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{ 
    <div class="profile-nav-wrapper">
        <ul class="profile-nav">
            <li>@Html.ActionLink("My Adopted Maps", "AdoptedMaps", "MyMaps")</li>
            <li><a href="@Url.Action("", "PublishedMaps", new { u = User.Identity.GetUserId() })">My Published Maps</a></li> 
            <li>@Html.ActionLink("My Profile", "Private", "Profile")</li>
            <li>@Html.ActionLink("Get More Tokens", "Credits", "Profile")</li>
        </ul>
    </div>
    <br/>
    <br/>
}

MyLegacyMaps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Legacy Maps</title>   
    @Styles.Render("~/content/css")
    @Scripts.Render("~/bundles/modernizr")  
    @Scripts.Render("~/bundles/jquery")     
</head>
<body>
    <div class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="mlm-logo-link" href="~/">
                    <img src="~/images/icons/MLM-REM-text-logo.png" alt="globe" class="mlm-logo">
                    <span>"Show your world"&trade;</span>
                </a>
                <img src="~/Images/mlm_home-pg_header_maps.png" alt="maps" class="mlm-header-maps" />
                @*@Html.ActionLink("My Legacy Maps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
             </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="menuitem">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="menuitem">@Html.ActionLink("Adventure Maps", "AdventureMaps", "Maps")</li> 
                    <li class="menuitem">@Html.ActionLink("Real Estate Maps", "RealEstateMaps", "Maps")</li>
                    <li class="menuitem">@Html.ActionLink("About", "About", "Home")</li>                 
                    <li>
                        @Html.Partial("_LoginPartial")
                    </li>               
                </ul>
                @Html.Partial("~/Views/Shared/ProfileNav.cshtml")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <ul class="horizontal-list">
                <li>&copy; @DateTime.Now.Year - S. Robert Sherby</li>
                <li>@Html.ActionLink("Terms And Conditions", "Terms", "Home")</li>
                <li>@Html.ActionLink("Privacy Policy", "Privacy", "Home")</li>
            </ul>        

            <p>Other Resources:</p>
            <div>

                <a href="http://www.premierpropertymaps.com/washington/king/capitolhill/wakingcapitolhill.php">
                    Capitol Hill Interactive Walking Map
                </a>
            </div>
            <div>
                <a href="http://www.premierpropertymaps.com/washington/jefferson/images/ppm2_ne_jeffco_face_map_500.png">
                    Port Townsend & Quimper Peninsula Relocation Guide Map
                </a>
            </div>
            <div>
                <a href="http://www.premierpropertymaps.com/washington/jefferson/images/ppm2_se_jeffco_face_map_500.png">
                    North Hood Canal Relocation Guide Map
                </a>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>