MyLegacyMaps/Models/AdoptedMap.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace MyLegacyMaps.Models
{
    public class AdoptedMap
    {        
        public AdoptedMap()
        {
            //prevent null ref exception
            Flags = new HashSet<Flag>();

            //Default to Private
            ShareStatusTypeId = 1;
            IsActive = true;
        }

        [Required]
        public int AdoptedMapId { get; set; } 
        [Required]
        public string UserId { get; set; }   
        [Required]
        public int MapId { get; set; }      
        [Required (ErrorMessage="Name is required")]
        [StringLength(60)]
        [RegularExpression(MyLegacyMaps.Constants.TEXT_REGEX, ErrorMessage = "Enter only alphabets and numbers for Name")]
        public string Name { get; set; }
        [RegularExpression(MyLegacyMaps.Constants.TEXT_REGEX, ErrorMessage = "Enter only alphabets and numbers for Name")]
        public string Description { get; set; }
        public bool IsActive { get; set; }

        [Required]
        public int ShareStatusTypeId { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }


        public bool IsShared()
        {
            return (ShareStatusTypeId != 1);
        }

        public virtual Map Map { get; set; }
        public virtual ShareStatusType ShareStatusType { get; set; }
        public virtual ICollection<Flag> Flags { get; set; }
    }
}

MyLegacyMaps/Controllers/MyMapsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

using PagedList;
using MLM.Logging;
using MLM.Persistence.Interfaces;
using MyLegacyMaps.Models;
using MyLegacyMaps.Extensions;
using MyLegacyMaps.Classes;
using MyLegacyMaps.Managers;



namespace MyLegacyMaps.Controllers
{
    public class MyMapsController : Controller
    {
        private IAdoptedMapsRepository adoptedMapsRepository = null;
        private ApplicationUserManager _userManager;
        private IPartnerLogosRepository logosRepository = null;
        private ILogger log = null;
       
        public MyMapsController(IAdoptedMapsRepository adoptedMapsResource, IPartnerLogosRepository logosResource, ILogger logger)
        {
            adoptedMapsRepository = adoptedMapsResource;
            logosRepository = logosResource;
            log = logger;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: AdoptedMaps
        public async Task<ActionResult> AdoptedMaps(int? page)
        {
            string userId = String.Empty;
            try
            {
                if (!HttpContext.User.Identity.IsAuthenticated)
                {
                    return new HttpUnauthorizedResult();
                }
                userId = User.Identity.GetUserId();
                var resp = await adoptedMapsRepository.GetAdoptedMapsByUserIdAsync(userId);

                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                ViewBag.HasAdoptedMaps = resp.Item.Count > 0;

                var mapsViewModel = (resp.Item.Count > 0)
                    ? resp.Item.ToViewModel().OrderBy(m => m.Name)
                    : new List<MyLegacyMaps.Models.AdoptedMap>().OrderBy(m => m.Name);              

                int pageNumber = (page ?? 1);
                return View(mapsViewModel.ToPagedList(pageNumber, Constants.PAGE_SIZE));
            }
            catch(Exception ex)
            {
                log.Error(ex, String.Format("Error in AdoptedMapsController GET Index UserId = {0}", userId));
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }      

        // GET: AdoptedMaps/Details/5
        public async Task<ActionResult> AdoptedMap(int? id)
        {
            try
            {
                if (!HttpContext.User.Identity.IsAuthenticated)
                {
                    return new HttpUnauthorizedResult();
                }
                if (!id.HasValue || (int)id <= 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var resp = await adoptedMapsRepository.GetAdoptedMapByIdAsync((int)id.Value);
                if(!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }
                return View(resp.Item.ToViewModel());
            }
            catch(Exception ex)
            {
                log.Error(ex, "Error in AdoptedMapsController GET Details id = {0} ", 
                    (id.HasValue)? id.Value.ToString() : "null");
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: SharedMaps 
        [AllowAnonymous]
        public async Task<ActionResult> SharedMaps(int? page)
        {
            string userId = String.Empty;
            try
            {
                if (!HttpContext.User.Identity.IsAuthenticated)
                {
                    return new HttpUnauthorizedResult();
                }

                userId = HttpContext.User.Identity.GetUserId();
                if (String.IsNullOrEmpty(userId))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var applicationUser = await UserManager.FindByIdAsync(userId);
                if (applicationUser == null)
                {
                    return HttpNotFound();
                }               
                
                var resp = await adoptedMapsRepository.GetPublicAdoptedMapsByUserIdAsync(userId);
                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                ViewBag.HasSharedMaps = resp.Item.Count > 0;
                ViewBag.DisplayName = applicationUser.DisplayName;

                var mapsViewModel = (resp.Item.Count > 0)
                    ? resp.Item.ToViewModel().OrderBy(m => m.Name)
                    : new List<MyLegacyMaps.Models.AdoptedMap>().OrderBy(m => m.Name);
                            

                int pageNumber = (page ?? 1);                            
                return View(mapsViewModel.ToPagedList(pageNumber, Constants.PAGE_SIZE));
            }
            catch (Exception ex)
            {
                log.Error(ex, String.Format("Error in AdoptedMapsController GET Index UserId = {0}", userId));
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: SharedMaps 
        [AllowAnonymous]
        public async Task<ActionResult> SharedMapsByUserId(string userId, int? page)
        {
            // string userId = String.Empty;
            try
            {
                if (String.IsNullOrEmpty(userId))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var resp = await adoptedMapsRepository.GetPublicAdoptedMapsByUserIdAsync(userId);
                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }
                            
                int pageNumber = (page ?? 1);
                var mapsViewModel = resp.Item.ToViewModel().OrderBy(m => m.Name);
                return View(mapsViewModel.ToPagedList(pageNumber, Constants.PAGE_SIZE));
            }
            catch (Exception ex)
            {
                log.Error(ex, String.Format("Error in AdoptedMapsController GET Index UserId = {0}", userId));
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: AdoptedMaps/Details/5
        [AllowAnonymous]
        public async Task<ActionResult> SharedMap(int? id)
        {
            try
            {
                if (!id.HasValue || (int)id <= 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var resp = await adoptedMapsRepository.GetAdoptedMapByIdAsync((int)id.Value);
                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }
                if(resp.Item.ShareStatusTypeId != (int)Enums.ShareStatusType.Public)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
                }
                return View(resp.Item.ToViewModel());
            }
            catch (Exception ex)
            {
                log.Error(ex, "Error in AdoptedMapsController GET SharedMap id = {0} ",
                    (id.HasValue) ? id.Value.ToString() : "null");
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: AdoptedMaps/Details/5
        public async Task<ActionResult> RealEstateMap(int? id)
        {
            try
            {
                if (!HttpContext.User.Identity.IsAuthenticated)
                {
                    return new HttpUnauthorizedResult();
                }
                if (!id.HasValue || (int)id <= 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var resp = await adoptedMapsRepository.GetAdoptedMapByIdAsync((int)id.Value);
                if (!resp.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                var respLogos = await logosRepository.GetPartnerLogosAsync();
                if (!respLogos.IsSuccess())
                {
                    return new HttpStatusCodeResult(resp.HttpStatusCode);
                }

                ViewBag.PartnerLogos = respLogos.Item.ToViewModel();
                return View(resp.Item.ToViewModel());
            }
            catch (Exception ex)
            {
                log.Error(ex, "Error in AdoptedMapsController GET RealEstateMap id = {0} ",
                    (id.HasValue) ? id.Value.ToString() : "null");
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // POST: MyMaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MapId, Name, Description")] AdoptedMap adoptedMap)
        {
            try
            { 
                if (!HttpContext.User.Identity.IsAuthenticated)
                {
                    return new HttpUnauthorizedResult();
                }               

MyLegacyMaps/Views/MyMaps/AdoptedMap.cshtml
@model MyLegacyMaps.Models.AdoptedMap

@{
    ViewBag.Title = "Adopted Map";
    var flagElem = "\"<a href='#' class='mlm-flag-lnk'><div class='makeMeDraggable draggableFlag {0} masterTooltip' data-xpos='{1}' data-ypos='{2}' " +
                         "data-flagtypeid={3} data-flagId={4} style='{5}' title='Name: {6} Date: {7} ' ></div></a>\"";                        
}

@section Scripts{      
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mlm")
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken();
    @Html.Hidden("adoptedMapId", Model.AdoptedMapId);
    @Html.Hidden("mapImageUrl", Model.Map.GetMainImageUrl())
    @Html.Hidden("mapCanvasHeight", Model.Map.GetCanvasHeight())
    @Html.Hidden("mapCanvasWidth", Model.Map.GetCanvasWidth())

    
}
@Html.Partial("~/Views/Shared/ProfileNav.cshtml")
@Html.Partial("~/Views/Shared/Partials/AdoptedMapCanvas.cshtml", Model.Map)

<script type="text/javascript">
    $(document).ready(function () {
        @foreach(var flag in @Model.Flags)
        {                        
            var elem =
                String.Format(flagElem,
                              flag.GetCssClass(),
                              flag.Xpos,
                              flag.Ypos,
                              flag.FlagTypeId,
                              flag.FlagId,
                              @Html.AttributeEncode(flag.GetStyle()),
                              @Html.AttributeEncode(flag.Name),
                              (flag.Date.HasValue)? flag.Date.Value.ToShortDateString() : "");
           
            @Html.Raw(String.Format("$('#canvas').append({0}); MLM.MapCanvas.wireUpFlags();", elem));
        }
    });
</script>

<h2>Map Details</h2> 
<p>
    Shared Status: @Html.DisplayFor(model => model.ShareStatusType.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
</p>
<p>
    @Html.ActionLink("Edit Map Details", "Edit", new { id = Model.AdoptedMapId }) | @Html.ActionLink("Delete Map", "Delete", new { id = Model.AdoptedMapId })
</p>
   

MyLegacyMaps/Views/MyMaps/AdoptedMaps.cshtml
@model PagedList.IPagedList<MyLegacyMaps.Models.AdoptedMap>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Adopted Maps";
    var realEstateMapType = new MyLegacyMaps.Models.MapType{ MapTypeId =1, Name = "Real Estate", IsActive=true };
}

@if (!ViewBag.HasAdoptedMaps)
{
    <p style="height:500px;">
        You have not yet Adopted any maps. Please browse our collection of @Html.ActionLink("Maps", "Index", "Maps"). To Adopt
        a map simple click on the map of interest and from the Map Details page, click the "Save" button. This will save the map
        to your adopted maps collection here. Once you've adopted a map you can start adding flags, photos and videos. Enjoy!
    </p>

}
else
{
    <div class="grid">
        @foreach (var item in Model)
        {
            if (item.Map.OrientationTypeId == 1)
            {
                <div class="grid-item">

                    <a class="lnkGridItem" @(item.IsShared() ? "title=Shared" : "title=Private") href="@Url.Action(item.Map.IsRealEstateMap()? "RealEstateMap":"AdoptedMap", new { id = item.AdoptedMapId })">
                        <img src="@item.Map.GetThumbImageUrl()" height="167" width="250" @(item.IsShared() ? "class=grid-thumb-shared" : "")>
                        <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                        <p class="grid-item-text">@Html.DisplayFor(modelItem => item.Description)</p>
                    </a>
                </div>
            }
            else
            {
                <div class="grid-item vertical-item">

                    <a class="lnkGridItem" @(item.IsShared() ? "title=Shared" : "title=Private") href="@Url.Action(item.Map.IsRealEstateMap() ? "RealEstateMap" : "AdoptedMap", new { id = item.AdoptedMapId })">
                        <img src="@item.Map.GetThumbImageUrl()" height="315" width="210" @(item.IsShared() ? "class=grid-thumb-shared" : "")>
                        <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                        <p class="grid-item-text">@Html.DisplayFor(modelItem => item.Description)</p>
                    </a>
                </div>
            }
        }
    </div>


    <script>
        $(document).ready(function () {

            $('.grid').masonry({
                itemSelector: '.grid-item',
                columnWidth: 310
            });

        });
    </script>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("AdoptedMaps",
        new { page }))

MyLegacyMaps/Views/MyMaps/Delete.cshtml
@model MyLegacyMaps.Models.AdoptedMap

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Map</h2>

<h3>Are you sure you want to delete this map?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">        
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Flags
        </dt>

        <dd>
          @Html.Raw(Model.Flags.Count.ToString())
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "MyMaps", FormMethod.Post, new { id = "frmDeleteMap" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            &nbsp;|&nbsp;@Html.ActionLink("Cancel", "AdoptedMap", "MyMaps", new { id = Model.AdoptedMapId }, null)           
        </div>
    }
</div>

MyLegacyMaps/Views/MyMaps/Edit.cshtml
@model MyLegacyMaps.Models.AdoptedMap
@using MyLegacyMaps.Models;

@{
    ViewBag.Title = "Edit Adopted Map";
}

<h3>Edit Map Details</h3>


@using (Html.BeginForm("Edit", "MyMaps", FormMethod.Post, new { id = "frmEditMapDetials" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AdoptedMapId)
        @Html.HiddenFor(model => model.ShareStatusTypeId)
        @Html.HiddenFor(model => model.MapId) 
        @Html.HiddenFor(model => model.DateCreated)    
        @Html.HiddenFor(model => model.UserId)    

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Sharing</label>
            <div class="col-md-10">
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="ddlOrientation"
                            data-toggle="dropdown">
                       <span>Choose:</span><span class="caret"></span>
                    </button>
                    &nbsp;<label id="ddlShareStatusSelectedVal">@Html.DisplayFor(model => model.ShareStatusType.Name)</label>
                    <ul class="dropdown-menu" role="menu">
                        @foreach (var type in (List<ShareStatusType>)ViewBag.ShareTypes)
                        {
                            <li role="presentation" onclick="onShareStatusTypeSelected('@type.ShareStatusTypeId', '@type.Name')">
                                <a role="menuitem" href="#">@type.Name</a>
                            </li>
                        } 
                    </ul>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                &nbsp;|&nbsp;@Html.ActionLink("Cancel", (Model.Map.IsRealEstateMap())? "RealEstateMap" : "AdoptedMap", "MyMaps", new { id = Model.AdoptedMapId }, null)
            </div>
        </div>
    </div>
}

<div>
    
    <script type="text/javascript">
        function onShareStatusTypeSelected(id, value) {
            $('#ddlShareStatusSelectedVal').text(value);
            $('#ShareStatusTypeId').val(id);
        }
    </script>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyLegacyMaps/Views/MyMaps/RealEstateMap.cshtml
@model MyLegacyMaps.Models.AdoptedMap

@{
    ViewBag.Title = "MyLegacyMaps - Real Estate Map Details";
    var flagElem = "\"<a href='#' class='mlm-flag-lnk'><div  class='makeMeDraggable {0} masterTooltip' data-xpos='{1}' data-ypos='{2}' " +
                        "data-flagtypeid={3} data-flagId={4} style='{5}' title='Name: {6} Date: {7} ' ></div></a>\"";
}

@section Scripts{
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mlm")
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.Hidden("adoptedMapId", Model.AdoptedMapId);
    @Html.Hidden("mapImageUrl", Model.Map.GetMainImageUrl())
    @Html.Hidden("mapCanvasHeight", Model.Map.GetCanvasHeight())
    @Html.Hidden("mapCanvasWidth", Model.Map.GetCanvasWidth())
}

@Html.Partial("~/Views/Shared/Partials/AdoptedRealEstateMapCanvas.cshtml", Model.Map)


<h2>Map Details</h2>
<p>
    Shared Status: @Html.DisplayFor(model => model.ShareStatusType.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
</p>
<p>
    @Html.ActionLink("Edit Map Details", "Edit", new { id = Model.AdoptedMapId }) | @Html.ActionLink("Delete Map", "Delete", new { id = Model.AdoptedMapId })
</p>

<script type="text/javascript">
    $(document).ready(function () {
        @foreach(var flag in @Model.Flags)
        {
            var elem =
                String.Format(flagElem,
                              flag.GetCssClass(),
                              flag.Xpos,
                              flag.Ypos,
                              flag.FlagTypeId,
                              flag.FlagId,
                              @Html.AttributeEncode(flag.GetStyle()),
                              @Html.AttributeEncode(flag.Name),
                              flag.DateModified.ToShortDateString());

            @Html.Raw(String.Format("$('#canvas').append({0}); MLM.MapCanvas.wireUpFlags();", elem));
        }
    });
</script>

MyLegacyMaps/Views/MyMaps/SharedMap.cshtml
@model MyLegacyMaps.Models.AdoptedMap

@{
    ViewBag.Title = "Adopted Map";
    var flagElem = "\"<a href='#' class='mlm-flag-lnk'><div  class='makeMeDraggable locked {0} masterTooltip' data-xpos='{1}' data-ypos='{2}' " +
                         "data-flagtypeid={3} data-flagId={4} style='{5}' title='Name: {6} Date: {7} ' ></div></a>\"";
}

@section Scripts{
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mlm")
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.Hidden("adoptedMapId", Model.AdoptedMapId);
    @Html.Hidden("mapImageUrl", Model.Map.GetMainImageUrl())
    @Html.Hidden("mapCanvasHeight", Model.Map.GetCanvasHeight())
    @Html.Hidden("mapCanvasWidth", Model.Map.GetCanvasWidth())


}

@Html.Partial("~/Views/Shared/Partials/SharedMapCanvas.cshtml", Model.Map)

<script type="text/javascript">
    $(document).ready(function () {
        @foreach(var flag in @Model.Flags)
        {
            var elem =
                String.Format(flagElem,
                              flag.GetCssClass(),
                              flag.Xpos,
                              flag.Ypos,
                              flag.FlagTypeId,
                              flag.FlagId,
                              @Html.AttributeEncode(flag.GetStyle()),
                              @Html.AttributeEncode(flag.Name),
                              (flag.Date.HasValue)? flag.Date.Value.ToShortDateString() : "");

            @Html.Raw(String.Format("$('#canvas').append({0}); MLM.MapCanvas.wireUpFlagOnClickEvents();", elem));
        }
    });
</script>

MyLegacyMaps/Views/MyMaps/SharedMaps.cshtml
@model PagedList.IPagedList<MyLegacyMaps.Models.AdoptedMap>
@using PagedList.Mvc;
@using MyLegacyMaps.Models;
@{
    ViewBag.Title = "Shared Maps";
}

@if(!ViewBag.HasSharedMaps)
{ 
    <p>
        You have not yet shared any maps. To share a map, visit your @Html.ActionLink("Adopted Maps", "AdoptedMaps", "MyMaps") and
        click the map you would like to share with the public. From the map detail page change the share status to "public". That's 
        it, your shared map can now be found here under your "Shared Maps" and will be visible to anyone with the link.
    </p>
}
else 
{     
    <p>
        <h3>Maps By: @ViewBag.DisplayName</h3>
    </p>

    <div class="grid">
        @foreach (var item in Model)
        {
            if (item.Map.OrientationTypeId == 1)
            {
                <div class="grid-item">

                    <a class="lnkGridItem" href="@Url.Action("SharedMap", new { id = item.AdoptedMapId })">
                        <img src="@item.Map.GetThumbImageUrl()" height="167" width="250" class="mlm-li-thumb">
                        <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                        <p class="grid-item-text">@Html.DisplayFor(modelItem => item.Description)</p>
                    </a>
                </div>
            }
            else
            {
                <div class="grid-item vertical-item">

                    <a class="lnkGridItem" href="@Url.Action("SharedMap", new { id = item.AdoptedMapId })">
                        <img src="@item.Map.GetThumbImageUrl()" height="315" width="210" class="mlm-li-thumb">
                        <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                        <p class="grid-item-text">@Html.DisplayFor(modelItem => item.Description)</p>
                    </a>
                </div>
            }
        }
    </div>
  

    <script>
        $(document).ready(function () {

            $('.grid').masonry({
                itemSelector: '.grid-item',
                columnWidth: 310
            });

        });
    </script>
}
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("SharedMaps",
        new { page }))